language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt532 
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt53base qt53tools qt53connectivity
  - source /opt/qt53/bin/qt53-env.sh
  - cmake --version
  - qmake -v

script:
  - mkdir build/ && cd build/
  - cmake -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/usr/local" ..
  - make -j2 all
  - sudo make install

os:
  - linux
  - osx

